title: <p align="center"> Carlos De Leon </p>

logo: ""

description:
  <p align="center">
  <a href="pdf/CMEDResume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/cmeddata/">LinkedIn</a> |
  <a href="https://github.com/cmeddata">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing BS degree in Computer Science at San Francisco State University.
  <br><br>
  I am currently a DataJam Mentor at Pittsburgh DataWorks.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

