title: <p align="center"> Carlos De Leon </p>

logo: "images/picture-modified.png"

description:
  <p align="center">
  <a href="https://github.com/cmeddata/cmeddata.github.io/blob/b0a51cdea84167433919b1113e93651059bfd4bc/PDF/CMEDResumeFinal.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/cmeddata/">LinkedIn</a> |
  <a href="https://github.com/cmeddata">GitHub</a>
  </p>
  
  <p align="justify">
  - BS Computer Science
  <br><br>
  -Vice President of the Data Science Society @ SFSU
  <br><br>
  - Junior
  <br><br>
  - San Francisco State University
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

