title: <p align="center"> Carlos De Leon </p>

logo: "images/IMG_1852.jpg"

description:
  <p align="center">
  <a href="pdf/CMEDResume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/cmeddata/">LinkedIn</a> |
  <a href="https://github.com/cmeddata">GitHub</a>
  </p>
  
  <p align="justify">
  - BS Computer Science
  <br><br>
  - Junior
  <br><br>
  - San Francisco State University
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

